### PR TITLE
Added Rookis_bg.lua

### PR DESCRIPTION
**Pull request by Pdzly**
I added a plugin where the user can change the background to a url image (png or jpg)

### CODE REVIEW

**Comment by Pdzly** [comment]
i found a bug rn please not merge i will try to fix it

**Comment by djsime1** [comment]
I'd try to find a way to merge this as part of the existing background customizer by adding a "Background type" option. Otherwise I'm in the process of conceptualizing a system like you suggested in #7. If anything that system would be released with MPR v1.0.

**Comment by Pdzly** [comment]
Ok you could do it and cancel this then but i would like to have an idea what is my problem in my code it functions normally if you dont restart gmod after a restart it wont load my code correctly it wont call load() of my script but i used directly the code of the gradient_bg.lua code and i dont think its a bug its rather just me i tried to debug it with print(....) everywhere and it wont call the function at all but after reenabling it works

**Comment by djsime1** [comment]
Added to Plugin repo: https://github.com/djsime1/redux-plugins/blob/main/Pdzly/rookis_bg.lua
Open a PR there if you wish to update it further.

**Pull request closed without merging**
