### PR TITLE
Added a clock on top

### PR DESCRIPTION
**Pull request by Pdzly**

### CODE REVIEW

**Comment by Pdzly** [comment]
image

**Comment by Pdzly** [comment]
image

**Comment by djsime1** [comment]
The plugins you've submitted so far are neat, however I'm going to follow through with a secondary repository just for third party plugins. I'll close your PR's here, but I'll add them to the new repo with your permission.

**Comment by Pdzly** [comment]
yes ok would be great

**Comment by djsime1** [comment]
Added to Plugin repo: https://github.com/djsime1/redux-plugins/blob/main/Pdzly/rookis_time.lua
Open a PR there if you wish to update it further.

**Pull request closed without merging**
